steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app1:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app1:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'app1', '--image', 'gcr.io/$PROJECT_ID/app1:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--cpu', '1']

images:
  - 'gcr.io/$PROJECT_ID/app1:$SHORT_SHA'